@tool
extends RefCounted
class_name LocalizationService

static var _instance: LocalizationService = null

var _current_language := "en"
var _translations: Dictionary = {}

const AVAILABLE_LANGUAGES: Dictionary = {
	"en": "English",
	"zh_CN": "Simplified Chinese",
	"zh_TW": "Traditional Chinese",
	"ja": "Japanese",
	"ru": "Russian",
	"fr": "French",
	"pt": "Portuguese",
	"es": "Spanish",
	"de": "German"
}

const LANGUAGE_NATIVE_NAMES: Dictionary = {
	"en": "English",
	"zh_CN": "简体中文",
	"zh_TW": "繁體中文",
	"ja": "日本語",
	"ru": "Русский",
	"fr": "Français",
	"pt": "Português",
	"es": "Español",
	"de": "Deutsch"
}

const LANGUAGE_FILES: Dictionary = {
	"en": "res://addons/godot_dotnet_mcp/localization/locale_en.gd",
	"zh_CN": "res://addons/godot_dotnet_mcp/localization/locale_zh_cn.gd",
	"zh_TW": "res://addons/godot_dotnet_mcp/localization/locale_zh_tw.gd",
	"ja": "res://addons/godot_dotnet_mcp/localization/locale_ja.gd",
	"ru": "res://addons/godot_dotnet_mcp/localization/locale_ru.gd",
	"fr": "res://addons/godot_dotnet_mcp/localization/locale_fr.gd",
	"pt": "res://addons/godot_dotnet_mcp/localization/locale_pt.gd",
	"es": "res://addons/godot_dotnet_mcp/localization/locale_es.gd",
	"de": "res://addons/godot_dotnet_mcp/localization/locale_de.gd"
}

const SUPPLEMENTAL_TRANSLATIONS: Dictionary = {
	"en": {
		"dialog_title": "Godot MCP",
		"server_state_label": "State:",
		"active_connections": "Active Connections:",
		"total_requests": "Total Requests:",
		"total_connections_short": "connections",
		"last_request": "Last Request:",
		"last_request_none": "No requests yet",
		"btn_restart": "Restart",
		"btn_reload_plugin": "Reload Plugin",
		"tool_profile": "Profile:",
		"tool_profile_slim": "Slim",
		"tool_profile_default": "Default",
		"tool_profile_full": "Full",
		"tool_profile_slim_desc": "Enable the base Godot.NET inspection and editing tools, plus the plugin runtime tools used most often.",
		"tool_profile_default_desc": "Recommended everyday preset. Keeps base, plugin, gameplay, visual/animation and UI tools available.",
		"tool_profile_full_desc": "Expose every registered tool category.",
		"tool_profile_custom_desc": "Custom preset: %s",
		"tool_profile_modified_desc": "Current selection has been modified. Use Add to save it as a custom preset.",
		"tool_profile_save_title": "Save Custom Tool Preset",
		"tool_profile_save_desc": "Save the current tool selection as a reusable custom preset file.",
		"tool_profile_name_placeholder": "Preset name",
		"tool_profile_name_required": "Preset name is required",
		"tool_profile_saved": "Preset saved: %s",
		"tool_profile_save_failed": "Failed to save preset",
		"tool_profile_rename_title": "重命名自定义工具预设",
		"tool_profile_rename_desc": "重命名当前选中的自定义预设，并保留其已保存的工具选择。",
		"tool_profile_rename_failed": "重命名预设失败",
		"tool_profile_renamed": "预设已重命名：%s",
		"tool_profile_delete_title": "删除自定义工具预设",
		"tool_profile_delete_desc": "删除当前选中的自定义预设“%s”。",
		"tool_profile_delete_failed": "删除预设失败",
		"tool_profile_deleted": "预设已删除",
		"tool_profile_builtin_protected": "内建预设不允许重命名或删除",
		"tool_profile_not_found": "自定义预设不存在",
		"tool_profile_name_conflict": "已存在同名自定义预设",
		"btn_add_profile": "Add",
		"btn_rename_profile": "重命名",
		"btn_delete_profile": "删除",
		"btn_save_profile": "Save",
		"tools_load_errors": "Skipped %d tool categories due to script load errors. See editor output for details.",
		"domain_core": "Core",
		"domain_plugin": "Plugin",
		"domain_visual": "Visual",
		"domain_gameplay": "Gameplay",
		"domain_interface": "Interface",
		"domain_user": "User",
		"domain_other": "Other",
		"log_level": "Log Level:",
		"log_level_trace": "Trace",
		"log_level_debug": "Debug",
		"log_level_info": "Info",
		"log_level_warning": "Warning",
		"log_level_error": "Error",
		"show_user_tools": "Show User Category",
		"btn_delete_user_tool": "Delete User Tool",
		"tab_tools": "Tools",
		"tab_config": "Config",
		"settings": "Settings",
		"btn_stop": "Stop",
		"btn_expand_all": "Expand All",
		"btn_collapse_all": "Collapse All",
		"config_client_claude_desktop": "Claude Desktop",
		"config_client_cursor": "Cursor",
		"config_client_claude_code": "Claude Code",
		"config_client_codex": "Codex",
		"config_client_gemini": "Gemini",
		"config_header": "Connect Clients",
		"config_header_desc": "Use one-click file setup for desktop clients, or copy the verified command for CLI-based agents.",
		"config_platform": "Agent platform:",
		"config_section_desktop": "Config Files",
		"config_section_desktop_desc": "These clients read JSON config files. The generated snippet only updates the `godot-mcp` server entry.",
		"config_scope_claude": "Claude Code scope:",
		"config_file_path": "Config file path:",
		"config_client_claude_desktop_desc": "Writes the standard desktop config JSON using the MCP `url` field.",
		"config_client_cursor_desc": "Writes `~/.cursor/mcp.json` using the MCP `url` field.",
		"config_client_claude_code_desc": "Verified command based on Claude Code HTTP transport syntax and the selected scope.",
		"config_client_codex_desc": "Verified Codex CLI command using the official `codex mcp add <name> --url <url>` syntax.",
		"config_client_gemini_desc": "Writes `~/.gemini/settings.json` using `httpUrl`, which Gemini CLI currently expects for HTTP MCP servers.",
		"config_section_tools": "Tool Categories",
		"tools_toggle_column": "On",
		"tools_enabled_count": "Enabled",
		"btn_write_config": "Write Config",
		"tool_scene_run_name": "Run",
		"tool_node_transform_name": "Transform",
		"tool_node_property_name": "Property",
		"tool_node_process_name": "Process",
		"tool_node_metadata_name": "Metadata",
		"tool_resource_texture_name": "Texture",
		"tool_project_settings_name": "Settings",
		"tool_script_open_name": "Open",
		"tool_script_inspect_name": "Inspect",
		"tool_editor_settings_name": "Settings",
		"cat_user": "User",
		"tool_plugin_evolution_name": "Evolution",
		"tool_plugin_evolution_desc": "Create, audit and delete User-category tool scaffolds through MCP authorization",
		"tool_plugin_developer_name": "Developer",
		"tool_plugin_developer_desc": "Control developer-facing Dock options such as log level and User visibility",
		"permission_level": "Plugin Permission Level:",
		"permission_level_developer": "Developer Mode",
		"permission_level_evolution": "Evolution Mode",
		"permission_level_stable": "Stable Mode",
		"permission_denied_category": "Current permission level '%s' does not allow category '%s'.",
		"permission_denied_tool": "Current permission level '%s' does not allow tool '%s'.",
		"permission_denied_domain": "Current permission level '%s' does not allow domain '%s'.",
		"tool_plugin_runtime_usage_guide_name": "Usage Guide",
		"tool_plugin_runtime_usage_guide_desc": "Return the recommended runtime control and reload workflow for this plugin",
		"tool_plugin_evolution_usage_guide_name": "Usage Guide",
		"tool_plugin_evolution_usage_guide_desc": "Return the recommended authorization and User-tool workflow for this plugin",
		"tool_plugin_developer_usage_guide_name": "Usage Guide",
		"tool_plugin_developer_usage_guide_desc": "Return recommended plugin usage, reload policy and development/debug loop guidance",
		"language_name_en": "English",
		"language_name_zh_CN": "Simplified Chinese",
		"language_name_zh_TW": "Traditional Chinese",
		"language_name_ja": "Japanese",
		"language_name_ru": "Russian",
		"language_name_fr": "French",
		"language_name_pt": "Portuguese",
		"language_name_es": "Spanish",
		"language_name_de": "German"
	},
	"zh_CN": {
		"permission_level": "插件权限级别：",
		"permission_level_developer": "开发者模式",
		"permission_level_evolution": "自进化模式",
		"permission_level_stable": "稳定模式",
		"permission_denied_category": "当前权限级别“%s”不允许访问分类“%s”。",
		"permission_denied_tool": "当前权限级别“%s”不允许访问工具“%s”。",
		"permission_denied_domain": "当前权限级别“%s”不允许访问分组“%s”。",
		"tool_plugin_runtime_usage_guide_name": "使用指南",
		"tool_plugin_runtime_usage_guide_desc": "返回插件运行时控制、重载流程与调试建议",
		"tool_plugin_evolution_usage_guide_name": "使用指南",
		"tool_plugin_evolution_usage_guide_desc": "返回自进化授权流程、User 工具闭环与审计建议",
		"dialog_title": "Godot MCP",
		"server_state_label": "状态：",
		"active_connections": "活跃连接：",
		"total_requests": "总请求数：",
		"total_connections_short": "连接",
		"last_request": "最近请求：",
		"last_request_none": "暂无请求",
		"btn_restart": "重启",
		"btn_reload_plugin": "完全重载插件",
		"tool_profile": "预设：",
		"tool_profile_slim": "精简",
		"tool_profile_default": "默认",
		"tool_profile_full": "完整",
		"tool_profile_slim_desc": "仅启用 Godot.NET 项目中最常用的基础检查、编辑与插件运行时工具。",
		"tool_profile_default_desc": "推荐日常使用，保留基础、插件、玩法、视觉/动画与界面相关工具。",
		"tool_profile_full_desc": "启用当前注册的全部工具分类。",
		"tool_profile_custom_desc": "自定义预设：%s",
		"tool_profile_modified_desc": "当前选择已修改，可点击“新增”保存为自定义预设。",
		"tool_profile_save_title": "保存自定义工具预设",
		"tool_profile_save_desc": "将当前工具选择保存为可复用的自定义预设文件。",
		"tool_profile_name_placeholder": "输入预设名称",
		"tool_profile_name_required": "预设名称不能为空",
		"tool_profile_saved": "预设已保存：%s",
		"tool_profile_save_failed": "保存预设失败",
		"tool_profile_rename_title": "重命名自訂工具預設",
		"tool_profile_rename_desc": "重命名目前選中的自訂預設，並保留其已儲存的工具選擇。",
		"tool_profile_rename_failed": "重命名預設失敗",
		"tool_profile_renamed": "預設已重命名：%s",
		"tool_profile_delete_title": "刪除自訂工具預設",
		"tool_profile_delete_desc": "刪除目前選中的自訂預設「%s」。",
		"tool_profile_delete_failed": "刪除預設失敗",
		"tool_profile_deleted": "預設已刪除",
		"tool_profile_builtin_protected": "內建預設不允許重命名或刪除",
		"tool_profile_not_found": "自訂預設不存在",
		"tool_profile_name_conflict": "已存在同名自訂預設",
		"btn_add_profile": "新增",
		"btn_rename_profile": "重新命名",
		"btn_delete_profile": "刪除",
		"btn_save_profile": "保存",
		"tools_load_errors": "有 %d 个工具分类因脚本加载失败被跳过，请查看编辑器输出。",
		"domain_core": "核心",
		"domain_plugin": "插件",
		"domain_visual": "视觉",
		"domain_gameplay": "玩法",
		"domain_interface": "界面",
		"log_level": "日志等级：",
		"log_level_trace": "跟踪",
		"log_level_debug": "调试",
		"log_level_info": "信息",
		"log_level_warning": "警告",
		"log_level_error": "错误",
		"show_user_tools": "显示 User 分类",
		"btn_delete_user_tool": "删除用户工具",
		"domain_other": "其他",
		"tab_tools": "工具",
		"tab_config": "配置",
		"settings": "设置",
		"btn_stop": "停止",
		"btn_expand_all": "全部展开",
		"btn_collapse_all": "全部折叠",
		"config_client_claude_desktop": "Claude Desktop",
		"config_client_cursor": "Cursor",
		"config_client_claude_code": "Claude Code",
		"config_client_codex": "Codex",
		"config_client_gemini": "Gemini",
		"config_header": "连接客户端",
		"config_header_desc": "桌面客户端可直接一键写入配置，CLI 客户端则提供已核对的接入命令。",
		"config_platform": "Agent 平台：",
		"config_section_desktop": "配置文件",
		"config_section_desktop_desc": "这些客户端读取 JSON 配置文件。生成内容只会更新 `godot-mcp` 这一项，不覆盖其它服务器。",
		"config_scope_claude": "Claude Code 作用域：",
		"config_file_path": "配置文件路径：",
		"config_client_claude_desktop_desc": "写入标准桌面端配置，使用 MCP 的 `url` 字段。",
		"config_client_cursor_desc": "写入 `~/.cursor/mcp.json`，使用 MCP 的 `url` 字段。",
		"config_client_claude_code_desc": "按 Claude Code 官方 HTTP 传输命令格式生成，并带上当前作用域。",
		"config_client_codex_desc": "按官方 `codex mcp add <name> --url <url>` 语法生成。",
		"config_client_gemini_desc": "写入 `~/.gemini/settings.json`，对 HTTP MCP 服务使用 Gemini CLI 当前采用的 `httpUrl` 字段。",
		"config_section_tools": "工具分类",
		"tools_toggle_column": "开关",
		"tools_enabled_count": "启用情况",
		"btn_write_config": "写入配置",
		"tool_scene_run_name": "运行",
		"tool_node_transform_name": "变换",
		"tool_node_property_name": "属性",
		"tool_node_process_name": "处理",
		"tool_node_metadata_name": "元数据",
		"tool_resource_texture_name": "纹理",
		"tool_project_settings_name": "设置",
		"tool_script_open_name": "打开",
		"tool_script_inspect_name": "分析",
		"tool_editor_settings_name": "设置",
		"language_name_en": "英文",
		"language_name_zh_CN": "简体中文",
		"language_name_zh_TW": "繁体中文",
		"language_name_ja": "日语",
		"language_name_ru": "俄语",
		"language_name_fr": "法语",
		"language_name_pt": "葡萄牙语",
		"language_name_es": "西班牙语",
		"language_name_de": "德语",
		"cat_plugin_runtime": "运行时",
		"cat_plugin_evolution": "自进化",
		"cat_plugin_developer": "开发者工具",
		"domain_core_desc": "覆盖项目、编辑器与文件系统等基础能力，适合作为日常代理操作的默认分组。",
		"domain_plugin_desc": "用于操控 MCP 插件自身，包括运行时生命周期、受控自进化和 Dock 开发者选项。",
		"domain_visual_desc": "覆盖材质、着色器、灯光、动画与几何等视觉内容制作能力。",
		"domain_gameplay_desc": "覆盖物理、导航与音频等玩法运行时控制能力。",
		"domain_interface_desc": "覆盖界面布局、主题与控件配置能力。",
		"domain_user_desc": "通过自进化流程新增的用户工具，默认隐藏，并与内置分类隔离。",
		"domain_other_desc": "当前未归属到预定义根分组的工具分类。",
		"cat_plugin_runtime_desc": "插件运行时生命周期、域重载与启停状态控制。",
		"cat_plugin_evolution_desc": "受授权保护的用户工具脚手架、删除、列举与审计能力。",
		"cat_plugin_developer_desc": "面向 Dock 的开发者控制项，例如语言、预设与日志等级。",
		"tool_resource_create_name": "创建",
		"tool_resource_create_desc": "按资源类型创建新的资源文件",
		"tool_resource_file_ops_name": "资源文件操作",
		"tool_resource_file_ops_desc": "复制、移动、删除或重载资源文件",
		"tool_debug_log_write_name": "日志写入",
		"tool_debug_log_write_desc": "写入信息、警告、错误和富文本日志",
		"tool_debug_log_buffer_name": "日志缓冲区",
		"tool_debug_log_buffer_desc": "读取或清空 MCP 调试日志缓冲区",
		"tool_debug_runtime_bridge_name": "运行时桥接",
		"tool_debug_runtime_bridge_desc": "读取主项目运行时桥接事件与编辑器调试会话状态",
		"tool_filesystem_file_read_name": "文件读取",
		"tool_filesystem_file_read_desc": "读取文件内容并查看存在状态或元信息",
		"tool_filesystem_file_write_name": "文件写入",
		"tool_filesystem_file_write_desc": "写入或追加项目内的纯文本文件",
		"tool_filesystem_file_manage_name": "文件管理",
		"tool_filesystem_file_manage_desc": "删除、复制或移动项目内文件",
		"tool_plugin_runtime_state_name": "状态",
		"tool_plugin_runtime_state_desc": "读取已加载工具域、运行时摘要、调用统计与最近重载状态",
		"tool_plugin_runtime_reload_name": "重载",
		"tool_plugin_runtime_reload_desc": "重载工具域，或触发插件软重载与完整重载流程",
		"tool_plugin_runtime_server_name": "服务器",
		"tool_plugin_runtime_server_desc": "在不改动工具注册的前提下重启内置 MCP 服务器",
		"tool_plugin_runtime_toggle_name": "开关控制",
		"tool_plugin_runtime_toggle_desc": "启用或停用单个工具、分类或根分组",
		"tool_plugin_evolution_list_user_tools_name": "列出用户工具",
		"tool_plugin_evolution_list_user_tools_desc": "列出所有 User 分类工具及其来源脚本",
		"tool_plugin_evolution_scaffold_user_tool_name": "生成用户工具脚手架",
		"tool_plugin_evolution_scaffold_user_tool_desc": "在明确授权后预演或创建 User 分类工具脚手架",
		"tool_plugin_evolution_delete_user_tool_name": "删除用户工具",
		"tool_plugin_evolution_delete_user_tool_desc": "在明确授权后预演或删除 User 分类工具脚本",
		"tool_plugin_evolution_restore_user_tool_name": "恢复用户工具",
		"tool_plugin_evolution_restore_user_tool_desc": "预览或恢复最近一次删除的 User 分类工具脚本",
		"tool_plugin_evolution_user_tool_audit_name": "用户工具审计",
		"tool_plugin_evolution_user_tool_audit_desc": "读取最近的用户工具变更审计记录",
		"tool_plugin_developer_settings_name": "开发者设置",
		"tool_plugin_developer_settings_desc": "读取语言、预设、User 显隐等开发者向状态",
		"tool_plugin_developer_log_level_name": "日志等级",
		"tool_plugin_developer_log_level_desc": "修改插件调试缓冲区的最低日志等级",
		"tool_plugin_developer_user_visibility_name": "User 显隐",
		"tool_plugin_developer_user_visibility_desc": "切换 Dock 中是否显示 User 分类",
		"tool_plugin_developer_list_languages_name": "语言列表",
		"tool_plugin_developer_list_languages_desc": "列出可用界面语言与当前启用语言",
		"tool_plugin_developer_set_language_name": "设置语言",
		"tool_plugin_developer_set_language_desc": "切换插件 Dock 的显示语言",
		"tool_plugin_developer_list_profiles_name": "预设列表",
		"tool_plugin_developer_list_profiles_desc": "列出内置与自定义工具预设",
		"tool_plugin_developer_apply_profile_name": "应用预设",
		"tool_plugin_developer_apply_profile_desc": "将已保存的工具预设应用到当前启用状态",
		"tool_plugin_developer_save_profile_name": "保存预设",
		"tool_plugin_developer_save_profile_desc": "把当前工具选择保存为可复用的自定义预设",
		"tool_plugin_developer_rename_profile_name": "重命名预设",
		"tool_plugin_developer_rename_profile_desc": "重命名已保存的自定义工具预设",
		"tool_plugin_developer_delete_profile_name": "删除预设",
		"tool_plugin_developer_delete_profile_desc": "删除已保存的自定义工具预设",
		"tool_plugin_developer_usage_guide_name": "使用指南",
		"tool_plugin_developer_usage_guide_desc": "返回插件推荐使用方法、重载策略与开发调试闭环说明"
	},
	"zh_TW": {
		"permission_level": "外掛權限級別：",
		"permission_level_developer": "開發者模式",
		"permission_level_evolution": "自進化模式",
		"permission_level_stable": "穩定模式",
		"permission_denied_category": "目前權限級別「%s」不允許存取分類「%s」。",
		"permission_denied_tool": "目前權限級別「%s」不允許存取工具「%s」。",
		"permission_denied_domain": "目前權限級別「%s」不允許存取分組「%s」。",
		"tool_plugin_runtime_usage_guide_name": "使用指南",
		"tool_plugin_runtime_usage_guide_desc": "回傳外掛運行時控制、重載流程與調試建議",
		"tool_plugin_evolution_usage_guide_name": "使用指南",
		"tool_plugin_evolution_usage_guide_desc": "回傳自進化授權流程、User 工具閉環與審計建議",
		"dialog_title": "Godot MCP",
		"server_state_label": "狀態：",
		"active_connections": "活躍連線：",
		"total_requests": "總請求數：",
		"total_connections_short": "連線",
		"last_request": "最近請求：",
		"last_request_none": "暫無請求",
		"btn_restart": "重新啟動",
		"btn_reload_plugin": "完整重載外掛",
		"tool_profile": "預設：",
		"tool_profile_slim": "精簡",
		"tool_profile_default": "預設",
		"tool_profile_full": "完整",
		"tool_profile_slim_desc": "僅啟用 Godot.NET 專案中最常用的基礎檢查、編輯與外掛執行時工具。",
		"tool_profile_default_desc": "建議日常使用，保留基礎、外掛、玩法、視覺/動畫與介面工具。",
		"tool_profile_full_desc": "啟用目前註冊的全部工具分類。",
		"tool_profile_custom_desc": "自訂預設：%s",
		"tool_profile_modified_desc": "目前選擇已修改，可點擊「新增」另存為自訂預設。",
		"tool_profile_save_title": "儲存自訂工具預設",
		"tool_profile_save_desc": "將目前工具選擇儲存為可重用的自訂預設檔案。",
		"tool_profile_name_placeholder": "輸入預設名稱",
		"tool_profile_name_required": "預設名稱不能為空",
		"tool_profile_saved": "預設已儲存：%s",
		"tool_profile_save_failed": "儲存預設失敗",
		"btn_add_profile": "新增",
		"btn_save_profile": "儲存",
		"tools_load_errors": "有 %d 個工具分類因腳本載入失敗被跳過，請查看編輯器輸出。",
		"domain_core": "核心",
		"domain_plugin": "外掛",
		"domain_visual": "視覺",
		"domain_gameplay": "玩法",
		"domain_interface": "介面",
		"log_level": "日誌等級：",
		"log_level_trace": "追蹤",
		"log_level_debug": "偵錯",
		"log_level_info": "資訊",
		"log_level_warning": "警告",
		"log_level_error": "錯誤",
		"show_user_tools": "顯示 User 分類",
		"btn_delete_user_tool": "刪除使用者工具",
		"domain_other": "其他",
		"config_client_claude_desktop": "Claude Desktop",
		"config_client_cursor": "Cursor",
		"config_client_claude_code": "Claude Code",
		"config_client_codex": "Codex",
		"config_client_gemini": "Gemini",
		"language_name_en": "英文",
		"language_name_zh_CN": "簡體中文",
		"language_name_zh_TW": "繁體中文",
		"language_name_ja": "日文",
		"language_name_ru": "俄文",
		"language_name_fr": "法文",
		"language_name_pt": "葡萄牙文",
		"language_name_es": "西班牙文",
		"language_name_de": "德文",
		"cat_plugin_runtime": "執行時",
		"cat_plugin_evolution": "自進化",
		"cat_plugin_developer": "開發者工具",
		"domain_core_desc": "涵蓋專案、編輯器與檔案系統等基礎能力，適合作為日常代理操作的預設分組。",
		"domain_plugin_desc": "用於操控 MCP 外掛本身，包括執行時生命週期、受控自進化與 Dock 開發者選項。",
		"domain_visual_desc": "涵蓋材質、著色器、燈光、動畫與幾何等視覺內容製作能力。",
		"domain_gameplay_desc": "涵蓋物理、導航與音訊等玩法執行時控制能力。",
		"domain_interface_desc": "涵蓋介面版面、主題與控制節點設定能力。",
		"domain_user_desc": "透過自進化流程新增的使用者工具，預設隱藏，並與內建分類隔離。",
		"domain_other_desc": "目前尚未歸屬到預定義根分組的工具分類。",
		"cat_plugin_runtime_desc": "外掛執行時生命週期、域重載與啟停狀態控制。",
		"cat_plugin_evolution_desc": "受授權保護的使用者工具腳手架、刪除、列舉與稽核能力。",
		"cat_plugin_developer_desc": "面向 Dock 的開發者控制項，例如語言、預設與日誌等級。",
		"tool_resource_create_name": "建立",
		"tool_resource_create_desc": "依資源型別建立新的資源檔案",
		"tool_resource_file_ops_name": "資源檔案操作",
		"tool_resource_file_ops_desc": "複製、移動、刪除或重載資源檔案",
		"tool_debug_log_write_name": "日誌寫入",
		"tool_debug_log_write_desc": "寫入資訊、警告、錯誤與富文字日誌",
		"tool_debug_log_buffer_name": "日誌緩衝區",
		"tool_debug_log_buffer_desc": "讀取或清空 MCP 偵錯日誌緩衝區",
		"tool_debug_runtime_bridge_name": "運行時橋接",
		"tool_debug_runtime_bridge_desc": "讀取主專案運行時橋接事件與編輯器調試會話狀態",
		"tool_filesystem_file_read_name": "檔案讀取",
		"tool_filesystem_file_read_desc": "讀取檔案內容並查看存在狀態或中繼資訊",
		"tool_filesystem_file_write_name": "檔案寫入",
		"tool_filesystem_file_write_desc": "寫入或追加專案內的純文字檔案",
		"tool_filesystem_file_manage_name": "檔案管理",
		"tool_filesystem_file_manage_desc": "刪除、複製或移動專案內檔案",
		"tool_plugin_runtime_state_name": "狀態",
		"tool_plugin_runtime_state_desc": "讀取已載入工具域、執行時摘要、呼叫統計與最近重載狀態",
		"tool_plugin_runtime_reload_name": "重載",
		"tool_plugin_runtime_reload_desc": "重載工具域，或觸發外掛軟重載與完整重載流程",
		"tool_plugin_runtime_server_name": "伺服器",
		"tool_plugin_runtime_server_desc": "在不變更工具註冊的前提下重新啟動內建 MCP 伺服器",
		"tool_plugin_runtime_toggle_name": "開關控制",
		"tool_plugin_runtime_toggle_desc": "啟用或停用單一工具、分類或根分組",
		"tool_plugin_evolution_list_user_tools_name": "列出使用者工具",
		"tool_plugin_evolution_list_user_tools_desc": "列出所有 User 分類工具及其來源腳本",
		"tool_plugin_evolution_scaffold_user_tool_name": "產生使用者工具腳手架",
		"tool_plugin_evolution_scaffold_user_tool_desc": "在明確授權後預演或建立 User 分類工具腳手架",
		"tool_plugin_evolution_delete_user_tool_name": "刪除使用者工具",
		"tool_plugin_evolution_delete_user_tool_desc": "在明確授權後預演或刪除 User 分類工具腳本",
		"tool_plugin_evolution_restore_user_tool_name": "恢復使用者工具",
		"tool_plugin_evolution_restore_user_tool_desc": "預覽或恢復最近一次刪除的 User 分類工具腳本",
		"tool_plugin_evolution_user_tool_audit_name": "使用者工具稽核",
		"tool_plugin_evolution_user_tool_audit_desc": "讀取最近的使用者工具變更稽核紀錄",
		"tool_plugin_developer_settings_name": "開發者設定",
		"tool_plugin_developer_settings_desc": "讀取語言、預設、User 顯隱等開發者向狀態",
		"tool_plugin_developer_log_level_name": "日誌等級",
		"tool_plugin_developer_log_level_desc": "修改外掛偵錯緩衝區的最低日誌等級",
		"tool_plugin_developer_user_visibility_name": "User 顯隱",
		"tool_plugin_developer_user_visibility_desc": "切換 Dock 中是否顯示 User 分類",
		"tool_plugin_developer_list_languages_name": "語言列表",
		"tool_plugin_developer_list_languages_desc": "列出可用介面語言與目前啟用語言",
		"tool_plugin_developer_set_language_name": "設定語言",
		"tool_plugin_developer_set_language_desc": "切換外掛 Dock 的顯示語言",
		"tool_plugin_developer_list_profiles_name": "預設列表",
		"tool_plugin_developer_list_profiles_desc": "列出內建與自訂工具預設",
		"tool_plugin_developer_apply_profile_name": "套用預設",
		"tool_plugin_developer_apply_profile_desc": "將已儲存的工具預設套用到目前啟用狀態",
		"tool_plugin_developer_save_profile_name": "儲存預設",
		"tool_plugin_developer_save_profile_desc": "把目前工具選擇儲存為可重用的自訂預設",
		"tool_plugin_developer_rename_profile_name": "重命名預設",
		"tool_plugin_developer_rename_profile_desc": "重命名已儲存的自訂工具預設",
		"tool_plugin_developer_delete_profile_name": "刪除預設",
		"tool_plugin_developer_delete_profile_desc": "刪除已儲存的自訂工具預設",
		"tool_plugin_developer_usage_guide_name": "使用指南",
		"tool_plugin_developer_usage_guide_desc": "回傳外掛推薦使用方式、重載策略與開發調試閉環說明"
	},
	"ja": {
		"dialog_title": "Godot MCP",
		"server_state_label": "状態:",
		"active_connections": "アクティブ接続:",
		"total_requests": "総リクエスト数:",
		"total_connections_short": "接続",
		"last_request": "最新リクエスト:",
		"last_request_none": "まだリクエストはありません",
		"btn_restart": "再起動",
		"btn_reload_plugin": "プラグインを完全再読み込み",
		"tool_profile": "プリセット:",
		"tool_profile_slim": "簡易",
		"tool_profile_default": "標準",
		"tool_profile_full": "完全",
		"tool_profile_slim_desc": "Godot.NET プロジェクトで最もよく使う基礎確認・編集ツールとプラグイン実行時ツールのみを有効化します。",
		"tool_profile_default_desc": "日常利用向けの推奨プリセットです。基礎、プラグイン、ゲームプレイ、ビジュアル/アニメーション、UI ツールを残します。",
		"tool_profile_full_desc": "登録済みの全ツールカテゴリを公開します。",
		"tool_profile_custom_desc": "カスタムプリセット: %s",
		"tool_profile_modified_desc": "現在の選択は変更されています。追加からカスタムプリセットとして保存できます。",
		"tool_profile_save_title": "カスタムツールプリセットを保存",
		"tool_profile_save_desc": "現在のツール選択を再利用可能なカスタムプリセットとして保存します。",
		"tool_profile_name_placeholder": "プリセット名",
		"tool_profile_name_required": "プリセット名は必須です",
		"tool_profile_saved": "プリセットを保存しました: %s",
		"tool_profile_save_failed": "プリセットの保存に失敗しました",
		"btn_add_profile": "追加",
		"btn_save_profile": "保存",
		"tools_load_errors": "スクリプト読み込みエラーのため %d 個のツールカテゴリをスキップしました。詳細はエディター出力を確認してください。",
		"domain_core": "コア",
		"domain_plugin": "プラグイン",
		"domain_visual": "ビジュアル",
		"domain_gameplay": "ゲームプレイ",
		"domain_interface": "インターフェース",
		"log_level": "ログレベル:",
		"log_level_trace": "Trace",
		"log_level_debug": "Debug",
		"log_level_info": "Info",
		"log_level_warning": "Warning",
		"log_level_error": "Error",
		"show_user_tools": "User カテゴリを表示",
		"btn_delete_user_tool": "ユーザーツールを削除",
		"domain_other": "その他",
		"config_client_claude_desktop": "Claude Desktop",
		"config_client_cursor": "Cursor",
		"config_client_claude_code": "Claude Code",
		"config_client_codex": "Codex",
		"config_client_gemini": "Gemini",
		"language_name_en": "英語",
		"language_name_zh_CN": "簡体字中国語",
		"language_name_zh_TW": "繁体字中国語",
		"language_name_ja": "日本語",
		"language_name_ru": "ロシア語",
		"language_name_fr": "フランス語",
		"language_name_pt": "ポルトガル語",
		"language_name_es": "スペイン語",
		"language_name_de": "ドイツ語"
	},
	"ru": {
		"dialog_title": "Godot MCP",
		"server_state_label": "Состояние:",
		"active_connections": "Активные подключения:",
		"total_requests": "Всего запросов:",
		"total_connections_short": "подключения",
		"last_request": "Последний запрос:",
		"last_request_none": "Запросов пока нет",
		"btn_restart": "Перезапустить",
		"btn_reload_plugin": "Полностью перезагрузить плагин",
		"tool_profile": "Профиль:",
		"tool_profile_slim": "Минимальный",
		"tool_profile_default": "Стандартный",
		"tool_profile_full": "Полный",
		"tool_profile_slim_desc": "Включает только базовые инструменты проверки, редактирования и runtime плагина, которые чаще всего используются в проектах Godot.NET.",
		"tool_profile_default_desc": "Рекомендуемый ежедневный набор. Оставляет базовые, plugin, игровые, визуальные/анимационные и UI-инструменты.",
		"tool_profile_full_desc": "Открывает все зарегистрированные категории инструментов.",
		"tool_profile_custom_desc": "Пользовательский профиль: %s",
		"tool_profile_modified_desc": "Текущий выбор изменён. Используйте Добавить, чтобы сохранить его как пользовательский профиль.",
		"tool_profile_save_title": "Сохранить пользовательский профиль инструментов",
		"tool_profile_save_desc": "Сохранить текущий выбор инструментов как повторно используемый пользовательский профиль.",
		"tool_profile_name_placeholder": "Имя профиля",
		"tool_profile_name_required": "Имя профиля обязательно",
		"tool_profile_saved": "Профиль сохранён: %s",
		"tool_profile_save_failed": "Не удалось сохранить профиль",
		"btn_add_profile": "Добавить",
		"btn_save_profile": "Сохранить",
		"tools_load_errors": "Пропущено %d категорий инструментов из-за ошибок загрузки скриптов. Подробности в выводе редактора.",
		"domain_core": "Основа",
		"domain_plugin": "Плагин",
		"domain_visual": "Визуал",
		"domain_gameplay": "Геймплей",
		"domain_interface": "Интерфейс",
		"log_level": "Уровень лога:",
		"log_level_trace": "Trace",
		"log_level_debug": "Debug",
		"log_level_info": "Info",
		"log_level_warning": "Warning",
		"log_level_error": "Error",
		"show_user_tools": "Показывать категорию User",
		"btn_delete_user_tool": "Удалить пользовательский инструмент",
		"domain_other": "Другое",
		"config_client_claude_desktop": "Claude Desktop",
		"config_client_cursor": "Cursor",
		"config_client_claude_code": "Claude Code",
		"config_client_codex": "Codex",
		"config_client_gemini": "Gemini",
		"language_name_en": "английский",
		"language_name_zh_CN": "упрощённый китайский",
		"language_name_zh_TW": "традиционный китайский",
		"language_name_ja": "японский",
		"language_name_ru": "русский",
		"language_name_fr": "французский",
		"language_name_pt": "португальский",
		"language_name_es": "испанский",
		"language_name_de": "немецкий"
	},
	"fr": {
		"dialog_title": "Godot MCP",
		"server_state_label": "État :",
		"active_connections": "Connexions actives :",
		"total_requests": "Nombre total de requêtes :",
		"total_connections_short": "connexions",
		"last_request": "Dernière requête :",
		"last_request_none": "Aucune requête pour le moment",
		"btn_restart": "Redémarrer",
		"btn_reload_plugin": "Recharger complètement le plugin",
		"tool_profile": "Profil :",
		"tool_profile_slim": "Allégé",
		"tool_profile_default": "Par défaut",
		"tool_profile_full": "Complet",
		"tool_profile_slim_desc": "Active uniquement les outils de base d'inspection, d'édition et de runtime plugin les plus utilisés dans les projets Godot.NET.",
		"tool_profile_default_desc": "Préréglage recommandé au quotidien. Conserve les outils de base, plugin, gameplay, visuel/animation et UI.",
		"tool_profile_full_desc": "Expose toutes les catégories d'outils enregistrées.",
		"tool_profile_custom_desc": "Profil personnalisé : %s",
		"tool_profile_modified_desc": "La sélection actuelle a été modifiée. Utilisez Ajouter pour l'enregistrer comme profil personnalisé.",
		"tool_profile_save_title": "Enregistrer un profil d'outils personnalisé",
		"tool_profile_save_desc": "Enregistrer la sélection actuelle d'outils comme profil personnalisé réutilisable.",
		"tool_profile_name_placeholder": "Nom du profil",
		"tool_profile_name_required": "Le nom du profil est obligatoire",
		"tool_profile_saved": "Profil enregistré : %s",
		"tool_profile_save_failed": "Échec de l'enregistrement du profil",
		"btn_add_profile": "Ajouter",
		"btn_save_profile": "Enregistrer",
		"tools_load_errors": "%d catégories d'outils ont été ignorées à cause d'erreurs de chargement de script. Voir la sortie de l'éditeur.",
		"domain_core": "Noyau",
		"domain_plugin": "Plugin",
		"domain_visual": "Visuel",
		"domain_gameplay": "Gameplay",
		"domain_interface": "Interface",
		"log_level": "Niveau de log :",
		"log_level_trace": "Trace",
		"log_level_debug": "Debug",
		"log_level_info": "Info",
		"log_level_warning": "Warning",
		"log_level_error": "Error",
		"show_user_tools": "Afficher la catégorie User",
		"btn_delete_user_tool": "Supprimer l'outil utilisateur",
		"domain_other": "Autre",
		"config_client_claude_desktop": "Claude Desktop",
		"config_client_cursor": "Cursor",
		"config_client_claude_code": "Claude Code",
		"config_client_codex": "Codex",
		"config_client_gemini": "Gemini",
		"language_name_en": "anglais",
		"language_name_zh_CN": "chinois simplifié",
		"language_name_zh_TW": "chinois traditionnel",
		"language_name_ja": "japonais",
		"language_name_ru": "russe",
		"language_name_fr": "français",
		"language_name_pt": "portugais",
		"language_name_es": "espagnol",
		"language_name_de": "allemand"
	},
	"pt": {
		"dialog_title": "Godot MCP",
		"server_state_label": "Estado:",
		"active_connections": "Conexões ativas:",
		"total_requests": "Total de solicitações:",
		"total_connections_short": "conexões",
		"last_request": "Última solicitação:",
		"last_request_none": "Nenhuma solicitação ainda",
		"btn_restart": "Reiniciar",
		"btn_reload_plugin": "Recarregar plugin por completo",
		"tool_profile": "Perfil:",
		"tool_profile_slim": "Enxuto",
		"tool_profile_default": "Padrão",
		"tool_profile_full": "Completo",
		"tool_profile_slim_desc": "Ativa apenas as ferramentas base de inspeção, edição e runtime do plugin mais usadas em projetos Godot.NET.",
		"tool_profile_default_desc": "Predefinição recomendada para o dia a dia. Mantém ferramentas base, de plugin, gameplay, visual/animação e UI.",
		"tool_profile_full_desc": "Expõe todas as categorias de ferramentas registradas.",
		"tool_profile_custom_desc": "Perfil personalizado: %s",
		"tool_profile_modified_desc": "A seleção atual foi modificada. Use Adicionar para salvá-la como perfil personalizado.",
		"tool_profile_save_title": "Salvar perfil de ferramentas personalizado",
		"tool_profile_save_desc": "Salve a seleção atual de ferramentas como um perfil personalizado reutilizável.",
		"tool_profile_name_placeholder": "Nome do perfil",
		"tool_profile_name_required": "O nome do perfil é obrigatório",
		"tool_profile_saved": "Perfil salvo: %s",
		"tool_profile_save_failed": "Falha ao salvar o perfil",
		"btn_add_profile": "Adicionar",
		"btn_save_profile": "Salvar",
		"tools_load_errors": "%d categorias de ferramentas foram ignoradas devido a erros ao carregar scripts. Veja a saída do editor.",
		"domain_core": "Núcleo",
		"domain_plugin": "Plugin",
		"domain_visual": "Visual",
		"domain_gameplay": "Jogabilidade",
		"domain_interface": "Interface",
		"log_level": "Nível de log:",
		"log_level_trace": "Trace",
		"log_level_debug": "Debug",
		"log_level_info": "Info",
		"log_level_warning": "Warning",
		"log_level_error": "Error",
		"show_user_tools": "Mostrar categoria User",
		"btn_delete_user_tool": "Excluir ferramenta do usuário",
		"domain_other": "Outros",
		"config_client_claude_desktop": "Claude Desktop",
		"config_client_cursor": "Cursor",
		"config_client_claude_code": "Claude Code",
		"config_client_codex": "Codex",
		"config_client_gemini": "Gemini",
		"language_name_en": "inglês",
		"language_name_zh_CN": "chinês simplificado",
		"language_name_zh_TW": "chinês tradicional",
		"language_name_ja": "japonês",
		"language_name_ru": "russo",
		"language_name_fr": "francês",
		"language_name_pt": "português",
		"language_name_es": "espanhol",
		"language_name_de": "alemão"
	},
	"es": {
		"dialog_title": "Godot MCP",
		"server_state_label": "Estado:",
		"active_connections": "Conexiones activas:",
		"total_requests": "Solicitudes totales:",
		"total_connections_short": "conexiones",
		"last_request": "Última solicitud:",
		"last_request_none": "Aún no hay solicitudes",
		"btn_restart": "Reiniciar",
		"btn_reload_plugin": "Recargar complemento por completo",
		"tool_profile": "Perfil:",
		"tool_profile_slim": "Ligero",
		"tool_profile_default": "Predeterminado",
		"tool_profile_full": "Completo",
		"tool_profile_slim_desc": "Activa solo las herramientas base de inspección, edición y runtime del plugin más usadas en proyectos Godot.NET.",
		"tool_profile_default_desc": "Preajuste recomendado para el uso diario. Mantiene herramientas base, plugin, de gameplay, visual/animación y UI.",
		"tool_profile_full_desc": "Expone todas las categorías de herramientas registradas.",
		"tool_profile_custom_desc": "Perfil personalizado: %s",
		"tool_profile_modified_desc": "La selección actual ha sido modificada. Usa Agregar para guardarla como perfil personalizado.",
		"tool_profile_save_title": "Guardar perfil de herramientas personalizado",
		"tool_profile_save_desc": "Guarda la selección actual de herramientas como un perfil personalizado reutilizable.",
		"tool_profile_name_placeholder": "Nombre del perfil",
		"tool_profile_name_required": "El nombre del perfil es obligatorio",
		"tool_profile_saved": "Perfil guardado: %s",
		"tool_profile_save_failed": "No se pudo guardar el perfil",
		"btn_add_profile": "Agregar",
		"btn_save_profile": "Guardar",
		"tools_load_errors": "Se omitieron %d categorías de herramientas por errores al cargar scripts. Revisa la salida del editor.",
		"domain_core": "Núcleo",
		"domain_plugin": "Plugin",
		"domain_visual": "Visual",
		"domain_gameplay": "Jugabilidad",
		"domain_interface": "Interfaz",
		"log_level": "Nivel de log:",
		"log_level_trace": "Trace",
		"log_level_debug": "Debug",
		"log_level_info": "Info",
		"log_level_warning": "Warning",
		"log_level_error": "Error",
		"show_user_tools": "Mostrar categoría User",
		"btn_delete_user_tool": "Eliminar herramienta de usuario",
		"domain_other": "Otros",
		"config_client_claude_desktop": "Claude Desktop",
		"config_client_cursor": "Cursor",
		"config_client_claude_code": "Claude Code",
		"config_client_codex": "Codex",
		"config_client_gemini": "Gemini",
		"language_name_en": "inglés",
		"language_name_zh_CN": "chino simplificado",
		"language_name_zh_TW": "chino tradicional",
		"language_name_ja": "japonés",
		"language_name_ru": "ruso",
		"language_name_fr": "francés",
		"language_name_pt": "portugués",
		"language_name_es": "español",
		"language_name_de": "alemán"
	},
	"de": {
		"dialog_title": "Godot MCP",
		"server_state_label": "Status:",
		"active_connections": "Aktive Verbindungen:",
		"total_requests": "Gesamtanfragen:",
		"total_connections_short": "Verbindungen",
		"last_request": "Letzte Anfrage:",
		"last_request_none": "Noch keine Anfragen",
		"btn_restart": "Neu starten",
		"btn_reload_plugin": "Plugin vollständig neu laden",
		"tool_profile": "Profil:",
		"tool_profile_slim": "Schlank",
		"tool_profile_default": "Standard",
		"tool_profile_full": "Voll",
		"tool_profile_slim_desc": "Aktiviert nur die wichtigsten Basis-, Prüf-, Bearbeitungs- und Plugin-Laufzeitwerkzeuge, die in Godot.NET-Projekten am häufigsten verwendet werden.",
		"tool_profile_default_desc": "Empfohlenes Alltagsprofil. Behält Basis-, Plugin-, Gameplay-, Visual-/Animations- und UI-Werkzeuge bei.",
		"tool_profile_full_desc": "Stellt alle registrierten Werkzeugkategorien bereit.",
		"tool_profile_custom_desc": "Benutzerdefiniertes Profil: %s",
		"tool_profile_modified_desc": "Die aktuelle Auswahl wurde geändert. Mit Hinzufügen kannst du sie als benutzerdefiniertes Profil speichern.",
		"tool_profile_save_title": "Benutzerdefiniertes Werkzeugprofil speichern",
		"tool_profile_save_desc": "Speichert die aktuelle Werkzeugauswahl als wiederverwendbares benutzerdefiniertes Profil.",
		"tool_profile_name_placeholder": "Profilname",
		"tool_profile_name_required": "Profilname ist erforderlich",
		"tool_profile_saved": "Profil gespeichert: %s",
		"tool_profile_save_failed": "Profil konnte nicht gespeichert werden",
		"btn_add_profile": "Hinzufügen",
		"btn_save_profile": "Speichern",
		"tools_load_errors": "%d Werkzeugkategorien wurden wegen Skriptladefehlern übersprungen. Details siehe Editor-Ausgabe.",
		"domain_core": "Kern",
		"domain_plugin": "Plugin",
		"domain_visual": "Visuell",
		"domain_gameplay": "Gameplay",
		"domain_interface": "Oberfläche",
		"log_level": "Log-Stufe:",
		"log_level_trace": "Trace",
		"log_level_debug": "Debug",
		"log_level_info": "Info",
		"log_level_warning": "Warning",
		"log_level_error": "Error",
		"show_user_tools": "User-Kategorie anzeigen",
		"btn_delete_user_tool": "User-Tool löschen",
		"domain_other": "Andere",
		"config_client_claude_desktop": "Claude Desktop",
		"config_client_cursor": "Cursor",
		"config_client_claude_code": "Claude Code",
		"config_client_codex": "Codex",
		"config_client_gemini": "Gemini",
		"language_name_en": "Englisch",
		"language_name_zh_CN": "Vereinfachtes Chinesisch",
		"language_name_zh_TW": "Traditionelles Chinesisch",
		"language_name_ja": "Japanisch",
		"language_name_ru": "Russisch",
		"language_name_fr": "Französisch",
		"language_name_pt": "Portugiesisch",
		"language_name_es": "Spanisch",
		"language_name_de": "Deutsch"
	}
}

static func get_instance() -> LocalizationService:
	if _instance == null:
		_instance = LocalizationService.new()
		_instance._init_translations()
	return _instance


static func reset_instance() -> void:
	_instance = null


func _init_translations() -> void:
	_translations.clear()
	for lang_code in LANGUAGE_FILES:
		var file_path := str(LANGUAGE_FILES[lang_code])
		if not ResourceLoader.exists(file_path):
			continue
		var translations_value = _load_language_translations(file_path)
		if not (translations_value is Dictionary):
			continue
		_translations[lang_code] = _build_language_map(translations_value, SUPPLEMENTAL_TRANSLATIONS.get(lang_code, {}))

	_current_language = _detect_system_language()


func _load_language_translations(file_path: String):
	var lang_script = ResourceLoader.load(file_path, "", ResourceLoader.CACHE_MODE_REUSE)
	if lang_script == null:
		return {}

	if lang_script.has_method("get_translations"):
		return lang_script.call("get_translations")

	return lang_script.get("TRANSLATIONS")


func _build_language_map(base_translations, supplemental_translations) -> Dictionary:
	var merged := {}

	if base_translations is Dictionary:
		merged = (base_translations as Dictionary).duplicate(true)

	if supplemental_translations is Dictionary:
		var supplemental_copy := (supplemental_translations as Dictionary).duplicate(true)
		for key in supplemental_copy.keys():
			merged[key] = supplemental_copy[key]

	return merged


func _detect_system_language() -> String:
	var locale := OS.get_locale()
	if AVAILABLE_LANGUAGES.has(locale):
		return locale

	var lang_code := locale.split("_")[0]
	match lang_code:
		"zh":
			var lower_locale := locale.to_lower()
			if lower_locale.contains("tw") or lower_locale.contains("hk") or lower_locale.contains("hant"):
				return "zh_TW"
			return "zh_CN"
		"ja":
			return "ja"
		"ru":
			return "ru"
		"fr":
			return "fr"
		"pt":
			return "pt"
		"es":
			return "es"
		"de":
			return "de"
		_:
			return "en"


func set_language(lang_code: String) -> void:
	if lang_code.is_empty():
		_current_language = _detect_system_language()
		return
	if AVAILABLE_LANGUAGES.has(lang_code):
		_current_language = lang_code


func get_language() -> String:
	return _current_language


func get_available_languages() -> Dictionary:
	return AVAILABLE_LANGUAGES


func get_language_display_name(lang_code: String, current_lang: String = "") -> String:
	var resolved_lang := current_lang if not current_lang.is_empty() else _current_language
	var native_name = str(LANGUAGE_NATIVE_NAMES.get(lang_code, AVAILABLE_LANGUAGES.get(lang_code, lang_code)))
	var translated_name = get_text_for(resolved_lang, "language_name_%s" % lang_code)
	return "%s（%s）" % [native_name, translated_name]


func get_text_for(lang_code: String, key: String) -> String:
	var resolved_lang := lang_code if not lang_code.is_empty() else _current_language
	var current_translations: Dictionary = _translations.get(resolved_lang, {})
	if current_translations.has(key):
		return str(current_translations[key])

	if resolved_lang != "en":
		var english_translations: Dictionary = _translations.get("en", {})
		if english_translations.has(key):
			return str(english_translations[key])

	return key


func get_text(key: String) -> String:
	return get_text_for(_current_language, key)


static func translate(key: String) -> String:
	return get_instance().get_text(key)
